pipeline {
  agent any
  environment {
    scmUrl = 'https://github.com/mhanyc/lifeline_data_sync.git'
  }

  stages {
    stage('checkout git') {
      steps {
       echo 'Checkout..'

      }
    }
    stage('Build') {
      steps {
        echo 'Building..'
      }
    }
    stage('Test') {
      steps {
        echo 'Testing..'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying....'
      }
    }

  }
}
